config/routes.rb
Rails.application.routes.draw do
  root to: "pages#index"
  get 'pages/index'
  get 'dashboard/index'
  get 'public/concept/:id', to: 'public#concept', as: 'public_concept'
  get 'public/user/:id', to: 'public#user', as: 'public_user'

  resources :concepts

  devise_for :users
  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/sign_up" => "devise/registrations#new"
    # authenticated :user do
    #   root :to => 'concepts#index', as: :authenticated_root
    # end
  end
end

app/models/concept.rb
# == Schema Information
#
# Table name: concepts
#
#  id          :integer          not null, primary key
#  concept     :string
#  date        :datetime
#  description :text
#  difficulty  :integer
#  state       :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#

class Concept < ActiveRecord::Base
  belongs_to :user
  has_many :sources
  has_and_belongs_to_many :tags
  enum difficulty: [:easy, :medium, :hard]
  enum state: [:happy, :sad]
end

app/models/source.rb
# == Schema Information
#
# Table name: sources
#
#  id         :integer          not null, primary key
#  name       :string
#  url        :string
#  concept_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Source < ActiveRecord::Base
  belongs_to :concept
end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Tag < ActiveRecord::Base
  has_and_belongs_to_many :concepts
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime
#  updated_at             :datetime
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :concepts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    dashboard_index_path
  end
end

app/controllers/concepts_controller.rb
class ConceptsController < ApplicationController
    before_filter :fetch_concept, only: [:edit, :update, :destroy, :show ]

  def index
    @concepts = Concept.all.where(user_id: current_user)
    @concept = Concept.new
  end

  def new
    @concept = Concept.new
  end

  def create
    @concept = Concept.new(concepts_params)
    @concept.user = current_user
    @concept.save
    redirect_to @concept
  end

  def edit
    # @concept = Concept.find(params[ :id ])
     @concepts = Concept.all
  end

  def update
    # @concept = Concept.find(params[ :id ])
    @concept.update(concepts_params)
    redirect_to @concept
  end

  def destroy
    # @concept = Concept.find(params[ :id ])
    @concept.destroy
    redirect_to action: 'index'
  end

  def show
    # @concept = Concept.find(params[ :id ])
  end

  private
  def fetch_concept
     @concept = Concept.find(params[ :id ])
  end
  def concepts_params
    params.require(:concept).permit(:concept, :date,:description,:difficulty,:state)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @concepts = Concept.all.where(user_id: current_user)
    @concepts_by_date = @concepts.group_by { |concept| concept.date.strftime("%F") }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @lastconcepts =  Concept.last(5)
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def concept
    @concept = Concept.find(params[ :id ])
  end
   def user
    @user = User.find(params[ :id ])
    @concepts = Concept.all.where(user_id: params[ :id ])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
  def calendar(date = Date.today, &block)
    Calendar.new(self, date, block).table
  end

  class Calendar < Struct.new(:view, :date, :callback)
    HEADER = %w(Sunday Monday Tuesday Wednesday Thursday Friday Saturday)
    START_DAY = :sunday

    delegate :content_tag, to: :view

    def table
      content_tag :table, class: "calendar" do
        header + week_rows
      end
    end

    def header
      content_tag :tr do
        HEADER.map { |day| content_tag :th, day }.join.html_safe
      end
    end

    def week_rows
      weeks.map do |week|
        content_tag :tr do
          week.map { |day| day_cell(day) }.join.html_safe
        end
      end.join.html_safe
    end

    def day_cell(day)
      content_tag :td, view.capture(day, &callback), class: day_classes(day)
    end

    def day_classes(day)
      classes = []
      classes << "today" if day == Date.today
      classes << "notmonth" if day.month != date.month
      classes.empty? ? nil : classes.join(" ")
    end

    def weeks
      first = date.beginning_of_month.beginning_of_week(START_DAY)
      last = date.end_of_month.end_of_week(START_DAY)
      (first..last).to_a.in_groups_of(7)
    end
  end
end

app/helpers/concepts_helper.rb
module ConceptsHelper
  def data_organizer
      result = [{"name":"Easy","data":{"Difficulty":0}}, {"name":"Medium","data":{"Difficulty":0}}, {"name":"Hard","data":{"Difficulty":0}}]
      concept_data = Concept.group(:difficulty).where(user_id: current_user).count
      concept_data.each do |key, value|
        if key == 0
          result[0] = {"name":"Easy","data":{"Difficulty": concept_data[key]}}
        elsif key == 1
          result[1] = {"name":"Medium","data":{"Difficulty": concept_data[key]}}
        elsif key == 2
          result[2] = {"name":"Hard","data":{"Difficulty": concept_data[key]}}
        end 
      end
      result
  end

  def daily_average
    # init_time = Time.at(current_user.created_at)
    init_time = Time.at(Concept.order("created_at").first.created_at)
    last_time = Time.now
    days = (last_time - init_time)/(24*60*60)
    average = Concept.all.count/days
    average.round
  end

  def daily_concepts(start = Concept.order("created_at").first.created_at)
      (start.to_date..Date.today).map do |date|
       {
         label: date,
         y: Concept.where(created_at: date.beginning_of_day..date.end_of_day)
       }
     end
  end

  def daily_streak
    counter = 0
    daily_concepts.each do |concept|
      concept_array = concept[:y].each{ |x| puts x }
      if concept_array.empty?
        counter = 0
      else
        counter += 1
      end
    end
    counter
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/concepts/_form.html.erb
<%= bootstrap_form_for(@concept) do |f| %>
<div class='row'>
  <div class="col-sm-12">
    <%= f.text_field :concept %>
    <%= f.text_area :description %>
  </div>
</div>
<div class="row">
  <div class="col-sm-4">
    <%= f.date_field :date, value: Date.today %>
  </div>
  <div class="col-sm-4">
    <%= f.select :difficulty, options_for_select(Concept.difficulties.keys), { label: "Difficulty level:" }, { class: "selectpicker" } %>
  </div>
  <div class="col-sm-4">
    <%= f.select :state, options_for_select(Concept.states.keys), { label: "Mood:" }, { class: "selectpicker" } %>
  </div>
</div>
<%= link_to 'Cancel', concepts_path, class: "btn btn-default pull-left" %>
<%= f.submit class: "btn btn-primary pull-right" %>
<% end %>

app/views/concepts/_modal_new_concept.html.erb
<div id="create-concept" class="container modal fade modal-new-concept">
  <div class="card card-container modal-dialog">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h4 class="modal-title">New Concept</h4>
    </div>
    <div class="margin-2em">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/concepts/_tags.html.erb
<div class="col-lg-4">
  <h3>Tags:</h3>
  <ul class="list-group">
    <% @concepts.each do |concept| %>
    <li class="list-group-item"><%= concept.concept %></li>
    <% end %>
  </ul>
</div>

app/views/concepts/edit.html.erb
<div class="container">
  <div class="row">
    <%= render 'tags' %>
    <div class="concepts col-lg-8">
      <h3>Edit Concept: </h3>
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/concepts/index.html.erb
<div class="container">
  <div class="row">
    <%= render 'tags' %>
    <div class="concepts col-lg-8">
      <h3>Concepts: <%= link_to 'Create concept',new_concept_path, class: "btn btn-primary pull-right"  , "data-toggle" => "modal" , "data-target" => "#create-concept" %></h3>
      <hr>
      <% @concepts.each do |concept| %>
      <div class="concept row">
        <div class="col-lg-3">
          <h4><%= concept.concept %></h4>
          <p class="date"><%= concept.date.strftime("at %B %d - %Y") %></p>
          <%= link_to 'edit' , edit_concept_path(concept) %>
          <%= link_to 'delete' , concept_path(concept), method: :delete , data: {confirm: "are you sure you want to delete it?"}  %>
        </div>
        <div class="col-lg-9">
          <p><%= concept.description %></p>
        </div>
      </div>
      <hr>
      <% end %>
    </div>
  </div>
</div>
<%= render 'modal_new_concept' %>

app/views/concepts/new.html.erb
<h1>New Concept</h1>
<div class="row">
  <div class="col-lg-6">
    <%= render "form" %>
  </div>
</div>

app/views/concepts/show.html.erb
<div class="container">
  <h1><%= @concept.concept %> </h1>
  <br>
  <%= @concept.date %> <br>
  <%= @concept.description %> <br>
  <%= @concept.difficulty %> <br>
  <%= @concept.state %>
  <% if user_signed_in? %>
  <p>
    <%= link_to "Edit", edit_concept_path(@concept), class: "btn btn-default" %>
    <%= link_to 'Delete' , concept_path(@concept), method: :delete , class: "btn btn-danger", data: {confirm: "are you sure you want to delete it?"}  %>
    <%= link_to "OK", concepts_path , class: "btn btn-primary" %>
    <% end %>
  </p>
</div>

app/views/dashboard/index.html.erb
<div class=" container">
  <div class="row">
    <div class="col-md-6">
      <%= line_chart Concept.group_by_day(:created_at).where(user_id: current_user).count %>
    </div>
    <div class="col-md-6">
      <%= column_chart data_organizer, colors: ["#5cb85c", "#f0ad4e", "#d9534f"] %>
    </div>
  </div>
</div>
<div class=" container">
  <div class="row">
    <div class="col-md-4">
      <p><%= @concepts.count %></p>
      <p>Total de conceptos</p>
    </div>
    <div class="col-md-4">
      <p><%= daily_average %></p>
      <p>Promedio conceptos/día</p>
    </div>
    <div class="col-md-4">
      <p><%= daily_streak %></p>
      <p>Day streak</p>
    </div>
  </div>
</div>
<div class="container" id="concept">
  <%= calendar do |date| %>
  <%= date.day %>
  <ul>
    <% @concepts_by_date.each do |concept_date, concept| %>
    <% print "This is the date: "%>
    <% puts date %>
    <% print "This is the concept date: "%>
    <% puts concept_date %>
    <% puts date == concept_date.to_date %>
    <% print "This is a concept: "%>
    <% concept.each { |x| puts x.concept } %>
    <% if date == concept_date.to_date %>
    <% puts "I'm passing through here" %>
    <% concept.each do |concept_name| %>
    <li><%= link_to concept_name.concept, concept_name %></li>
    <% end %>
    <% end %>
    <% end %>
  </ul>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Settle', root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <div class="pull-right">
        <% if user_signed_in? %>
        <span class="dropdown">
          <a class="dropdown-toggle" id="menu1" data-toggle="dropdown">
            <strong><%= current_user.email %></strong>
            <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
              <li role="presentation"><%= link_to 'Edit profile', edit_user_registration_path %></li>
              <li role="presentation" class="divider"></li>
              <li role="presentation"><%= link_to 'Dashboard', dashboard_index_path %></li>
              <li role="presentation"><%= link_to 'Concepts', concepts_path %></li>

            </ul>
          </span>
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-default navbar-btn"  %>
          <% else %>
          <%= link_to "create user", sign_up_path, class: "btn btn-default navbar-btn" %>
          <%= link_to "Login", login_path, class: "btn btn-default navbar-btn" %>
          <% end %>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Settle</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
</head>
<body>
  <%= render 'layouts/navigation' %>
  <div class="container">
    <% if notice %>
    <span class="notice alert alert-success"><%= notice %></span>
    <% end %>
    <% if alert %>
    <span class="alert alert-danger"><%= alert %></span>
    <% end %>
  </div>

  <%= yield %>

</body>
</html>

app/views/pages/_form.html.erb
<%= form_for :user, url: session_path(:user), html: {:class => "form-signin"} do |f| %>
<%= f.email_field :email, class: "form-control", placeholder: "Email", option: {required: "required"} %>
<%= f.password_field :password , class: "form-control" , placeholder: "Password", required:"required" %>
<div id="remember" class="checkbox">
  <%= f.label :remember_me do %>
  <%= f.check_box :remember_me  %>Remember Me
  <% end %>
</div>
<%= f.submit 'Sign in' , class: "btn btn-lg btn-primary btn-block btn-signin" %>
<% end %>
<%= link_to "Forgot your password?", new_password_path(:user), class: "forgot-password" %>

app/views/pages/_modal_login.html.erb
  <div id="login" class="container modal fade">
    <div class="card card-container modal-dialog">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Login</h4>
      </div>
      <div class="margin-2em">
        <%= render 'form' %>
      </div>
    </div>
  </div>

app/views/pages/index.html.erb
<section class="section-pages-index">

  <header class="intro-header">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
          <div class="site-heading">
            <h1>Settle is the new way keep track <strong>of your knowledge</strong></h1>
            <p>
              <% if user_signed_in? %>
              <%= link_to "My Concepts", concepts_path, class: "btn btn-default btn-lg" %>
              <%= link_to "Dashboard", dashboard_index_path, class: "btn btn-default btn-lg" %>
              <% else %>
              <%= link_to "create account", new_user_registration_path, class: "btn btn-default btn-lg" %>
              <%= link_to "login", "login_modal", class: "btn btn-default btn-lg" , "data-toggle" => "modal" , "data-target" => "#login" %>
              <% end %>
            </p>
          </div>
        </div>
      </div>
    </div>
  </header>

  <%= render 'modal_login' %>

  <!-- Page Features -->
  <div class=" container lastest-concepts">
    <div class="row">
      <div class="block-grid-lg-4 block-grid-md-3 block-grid-sm-3 block-grid-xs-2">
        <% @lastconcepts.each do |concept| %>
        <div class="block-grid-item">
          <div class="thumbnail">
            <h3><%= concept.concept %></h3>
            <ul class="tags list-inline">
              <li><a href="#">Jquery</a></li>
              <li><a href="#">Html</a></li>
              <li><a href="#">CSS</a></li>
            </ul>
            <p class="small">Dificulty: <strong><%= concept.difficulty %></strong></p>
            <p>
              <%= link_to 'See Concept', public_concept_path(concept.id), class: "btn btn-default btn-sm" %>
            </p>
            <p class="small">by: <%= link_to "#{concept.user.email}", public_user_path(concept.user.id) %></p>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</section>